// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuVx6oGYFBKcHy_PC2eYOUh2iLP2r3sKs',
    appId: '1:883868931697:web:7c5b479a670397f99dedd0',
    messagingSenderId: '883868931697',
    projectId: 'badge-icon',
    authDomain: 'badge-icon.firebaseapp.com',
    databaseURL: 'https://badge-icon-default-rtdb.firebaseio.com',
    storageBucket: 'badge-icon.appspot.com',
    measurementId: 'G-5T052CNGNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWClATzTpdXt1wiKQ_PqOoPOsIb2hhe3k',
    appId: '1:883868931697:android:a888897ad0a437889dedd0',
    messagingSenderId: '883868931697',
    projectId: 'badge-icon',
    databaseURL: 'https://badge-icon-default-rtdb.firebaseio.com',
    storageBucket: 'badge-icon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFnpiH1HaLJviLYHKppVfSn5ukJZvLqWo',
    appId: '1:883868931697:ios:53b7b13227449e189dedd0',
    messagingSenderId: '883868931697',
    projectId: 'badge-icon',
    databaseURL: 'https://badge-icon-default-rtdb.firebaseio.com',
    storageBucket: 'badge-icon.appspot.com',
    iosBundleId: 'app.parth.badgeIcon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFnpiH1HaLJviLYHKppVfSn5ukJZvLqWo',
    appId: '1:883868931697:ios:53b7b13227449e189dedd0',
    messagingSenderId: '883868931697',
    projectId: 'badge-icon',
    databaseURL: 'https://badge-icon-default-rtdb.firebaseio.com',
    storageBucket: 'badge-icon.appspot.com',
    iosBundleId: 'app.parth.badgeIcon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuVx6oGYFBKcHy_PC2eYOUh2iLP2r3sKs',
    appId: '1:883868931697:web:c2941e012a06fd569dedd0',
    messagingSenderId: '883868931697',
    projectId: 'badge-icon',
    authDomain: 'badge-icon.firebaseapp.com',
    databaseURL: 'https://badge-icon-default-rtdb.firebaseio.com',
    storageBucket: 'badge-icon.appspot.com',
    measurementId: 'G-92Z26ERZ4S',
  );
}
